---
title: "Tutorial Caret"
author: "Luiz Fonseca"
date: "5 de dezembro de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Caret é a abreviação para Classification And REgression Training.

# Instalação

```{r, eval=FALSE}
library(tidyr)
library(dplyr)
library(caret)
```

```{r}
dados_eleicoes <- read.csv("eleicoes2014.csv", encoding="latin1")
dados_eleicoes <- dados_eleicoes %>% select(-cargo, -sequencial_candidato, -numero_cadidato, -nome, -setor_economico_receita, -setor_economico_despesa)
```


O processo de reamostragem pode ser feito usando k-fold cross-validation, leave-one-out cross-validation ou bootstrapping.

```{r}

lambdaGrid <- expand.grid(lambda = 10^seq(10, -2, length=100))

fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv", 
                           number = 10,
                           repeats = 10,
                           search = "random")  # busca aleatória de hiperparâmetros

model.cv <- train(votos ~ ., 
               data = dados_eleicoes,
               method = "ridge",
               trControl = fitControl,
               tuneGrid = lambdaGrid,
               preProcess = c('scale', 'center', 'nzv'),
               na.action = na.omit)

model.cv
```


```{r}
ggplot(varImp(model.cv))
ggplot(model.cv)
```

# Predições

```{r}
predictions <- predict(model.cv, mtcars)

predictions
```
```

